spring:
  datasource:
    url: jdbc:mysql://39.98.36.134:22100/phorcys?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: shac
    driver-class-name: com.mysql.cj.jdbc.Driver

remote:
  service:
    url: http://localhost:8080/getUserName
    name: s1
