dubbo:
  protocols:
    dubbo:
      name: dubbo
      port: -1
  application:
    name: storage-service
    register-mode: instance
  registry:
    address: nacos://127.0.0.1:8848
  consumer:
    check: false
server:
  port: 10001
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/biz?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: wonder@123
    driver-class-name: com.mysql.cj.jdbc.Driver
seata:
  tx-service-group: bs-group
  application-id: rm-storage
  service:
    vgroup-mapping:
      bs-group: default
  config:
    type: nacos
    nacos:
      server-addr: 127.0.0.1:8848
      group: SEATA_GROUP
      username: nacos
      password: nacos
      namespace: ""
  registry:
    type: nacos
    nacos:
      application: seata-server
      server-addr: 127.0.0.1:8848
      group: SEATA_GROUP
      username: nacos
      password: nacos